-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.
-- Source of truth: src/lib/data/seed.ts   (regenerate with `npm run seed:sql`)

begin;

delete from changelog_entries;
delete from votes;
delete from features;
delete from categories;

insert into categories (id, slug, name_ar, name_en, color, sort_order) values
  ('c1000000-0000-4000-8000-000000000001', 'whatsapp', 'واتساب', 'WhatsApp', '#25D366', 1),
  ('c1000000-0000-4000-8000-000000000002', 'inbox', 'صندوق الوارد', 'Inbox', '#4D6BFB', 2),
  ('c1000000-0000-4000-8000-000000000003', 'automation', 'الأتمتة', 'Automation', '#7A5AF8', 3),
  ('c1000000-0000-4000-8000-000000000004', 'reports', 'التقارير', 'Reports', '#2EA8FF', 4),
  ('c1000000-0000-4000-8000-000000000005', 'mobile', 'تطبيق الجوال', 'Mobile App', '#F79009', 5);

insert into features (
  id, title_ar, title_en, description_ar, description_en, status, category_id,
  vote_count, is_pinned, source, submitted_by_name, shipped_at, created_at, updated_at
) values
  ('f1000000-0000-4000-8000-000000000001', 'ردود جاهزة بالذكاء الاصطناعي', 'AI-suggested replies', 'اقتراحات فورية للرد على العميل بناءً على سياق المحادثة ونبرة علامتك التجارية، مع إمكانية تعديلها قبل الإرسال.', 'Instant reply suggestions based on the conversation context and your brand tone, editable before you send.',
   'in_progress', 'c1000000-0000-4000-8000-000000000003', 218, true, 'internal',
   null, null, '2026-07-02T09:00:00.000Z'::timestamptz, '2026-07-02T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000002', 'توزيع المحادثات تلقائيًا على الفريق', 'Automatic conversation routing', 'وزّع المحادثات الواردة على أعضاء الفريق حسب التخصص أو ساعات العمل أو حجم العمل الحالي، دون إسناد يدوي.', 'Route incoming conversations to teammates by skill, working hours, or current load — no manual assignment.',
   'in_progress', 'c1000000-0000-4000-8000-000000000002', 176, false, 'internal',
   null, null, '2026-07-16T09:00:00.000Z'::timestamptz, '2026-07-16T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000003', 'كتالوج المنتجات داخل واتساب', 'Product catalog inside WhatsApp', 'اعرض منتجاتك وأسعارها داخل المحادثة، ليضيفها العميل إلى السلة دون مغادرة واتساب.', 'Show products and prices inside the chat so customers can add to cart without leaving WhatsApp.',
   'in_progress', 'c1000000-0000-4000-8000-000000000001', 143, false, 'customer_submission',
   'متجر رفوف', null, '2026-07-29T09:00:00.000Z'::timestamptz, '2026-07-29T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000004', 'إشعارات فورية على تطبيق الجوال', 'Push notifications on mobile', 'إشعار فوري على هاتفك لكل محادثة جديدة أو إسناد جديد، مع إمكانية الرد من داخل الإشعار.', 'Get an instant push for every new conversation or assignment, and reply straight from the notification.',
   'in_progress', 'c1000000-0000-4000-8000-000000000005', 97, false, 'internal',
   null, null, '2026-08-12T09:00:00.000Z'::timestamptz, '2026-08-12T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000005', 'لوحة تحليلات لأداء الفريق', 'Team performance analytics', 'متوسط زمن الرد وعدد المحادثات المغلقة ورضا العملاء لكل موظف، في لوحة واحدة قابلة للتصدير.', 'Average response time, resolved conversations, and CSAT per agent — one exportable dashboard.',
   'planned', 'c1000000-0000-4000-8000-000000000004', 189, true, 'internal',
   null, null, '2026-07-10T09:00:00.000Z'::timestamptz, '2026-07-10T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000006', 'قوالب رسائل واتساب متعددة اللغات', 'Multilingual WhatsApp templates', 'أنشئ القالب مرة واحدة بالعربية والإنجليزية، ويختار فلوفو اللغة المناسبة حسب لغة العميل.', 'Write a template once in Arabic and English; Flovoo picks the right one based on the customer''s language.',
   'planned', 'c1000000-0000-4000-8000-000000000001', 134, false, 'internal',
   null, null, '2026-07-24T09:00:00.000Z'::timestamptz, '2026-07-24T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000007', 'ملاحظات داخلية على المحادثة', 'Internal notes on conversations', 'اكتب ملاحظة يراها فريقك وحده، واذكر زميلك بعلامة @ لضمّه إلى المحادثة.', 'Leave a note only your team can see, and @-mention a teammate to pull them into the conversation.',
   'planned', 'c1000000-0000-4000-8000-000000000002', 121, false, 'customer_submission',
   'عيادات نبض', null, '2026-08-05T09:00:00.000Z'::timestamptz, '2026-08-05T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000008', 'تقارير مجدولة على البريد', 'Scheduled email reports', 'استقبل ملخص أداء أسبوعيًا أو شهريًا على بريدك تلقائيًا، دون فتح لوحة التقارير.', 'Receive a weekly or monthly performance summary by email automatically — no need to open the dashboard.',
   'planned', 'c1000000-0000-4000-8000-000000000004', 76, false, 'internal',
   null, null, '2026-08-02T09:00:00.000Z'::timestamptz, '2026-08-02T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000009', 'دعم قناة تيك توك للرسائل', 'TikTok messaging channel', 'اجمع رسائل تيك توك في صندوق الوارد نفسه مع بقية القنوات، حتى لا يفوتك عميل.', 'Bring TikTok messages into the same inbox as your other channels so no customer slips through.',
   'under_review', 'c1000000-0000-4000-8000-000000000002', 158, true, 'customer_submission',
   'Nour A.', null, '2026-08-22T09:00:00.000Z'::timestamptz, '2026-08-22T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000010', 'روبوت حجز المواعيد', 'Appointment booking bot', 'دع العميل يحجز موعده بنفسه داخل المحادثة، ليُسجَّل مباشرة في تقويم فريقك.', 'Let customers book their own slot inside the chat, and have it land straight in your team calendar.',
   'under_review', 'c1000000-0000-4000-8000-000000000003', 112, false, 'customer_submission',
   'صالون لمسة', null, '2026-08-27T09:00:00.000Z'::timestamptz, '2026-08-27T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000011', 'الوضع الليلي في التطبيق', 'Dark mode', 'وضع ليلي مريح للعين لفرق الدعم التي تعمل في الورديات المسائية.', 'An easy-on-the-eyes dark theme for support teams working evening shifts.',
   'under_review', 'c1000000-0000-4000-8000-000000000005', 88, false, 'customer_submission',
   'Hassan M.', null, '2026-08-11T09:00:00.000Z'::timestamptz, '2026-08-11T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000012', 'بحث ذكي داخل كل المحادثات', 'Smart search across conversations', 'ابحث بالمعنى لا بالكلمة الحرفية، مع تصفية حسب القناة أو الموظف أو الفترة الزمنية.', 'Search by meaning rather than exact wording, with filters for channel, agent, and date range.',
   'under_review', 'c1000000-0000-4000-8000-000000000002', 64, false, 'internal',
   null, null, '2026-08-31T09:00:00.000Z'::timestamptz, '2026-08-31T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000013', 'تصدير المحادثات إلى ملف', 'Export conversations to a file', 'نزّل أرشيف محادثاتك بصيغة CSV أو PDF للمراجعة أو الأرشفة الداخلية.', 'Download your conversation archive as CSV or PDF for review or internal record-keeping.',
   'under_review', 'c1000000-0000-4000-8000-000000000004', 41, false, 'customer_submission',
   'شركة مدار', null, '2026-09-01T09:00:00.000Z'::timestamptz, '2026-09-01T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000014', 'الرد السريع بالاختصارات', 'Saved replies with shortcuts', 'احفظ ردودك المتكررة واستدعها باختصار قصير أثناء الكتابة.', 'Save your repeated answers and recall them with a short shortcut while typing.',
   'shipped', 'c1000000-0000-4000-8000-000000000002', 204, false, 'internal',
   null, '2026-08-15T09:00:00.000Z'::timestamptz, '2026-05-05T09:00:00.000Z'::timestamptz, '2026-05-05T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000015', 'ربط إنستغرام دايركت', 'Instagram Direct integration', 'رسائل إنستغرام المباشرة والتعليقات أصبحت داخل صندوق وارد فلوفو مع بقية القنوات.', 'Instagram Direct messages and comments now land in the Flovoo inbox alongside your other channels.',
   'shipped', 'c1000000-0000-4000-8000-000000000001', 167, false, 'internal',
   null, '2026-07-18T09:00:00.000Z'::timestamptz, '2026-04-05T09:00:00.000Z'::timestamptz, '2026-04-05T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000016', 'تعدد المستخدمين والصلاحيات', 'Team seats and permissions', 'أضف فريقك بأدوار مختلفة — مدير، موظف دعم، مراقب — ويرى كل عضو ما يخصه وحده.', 'Add your team with distinct roles — admin, agent, viewer — so everyone sees only what concerns them.',
   'shipped', 'c1000000-0000-4000-8000-000000000002', 131, false, 'internal',
   null, '2026-06-19T09:00:00.000Z'::timestamptz, '2026-02-24T09:00:00.000Z'::timestamptz, '2026-02-24T09:00:00.000Z'::timestamptz),
  ('f1000000-0000-4000-8000-000000000017', 'دعم قناة فايبر', 'Viber channel support', 'مدمجة في طلب أوسع لدعم القنوات الإقليمية.', 'Merged into a broader request for regional channel support.',
   'archived', 'c1000000-0000-4000-8000-000000000002', 12, false, 'customer_submission',
   'Karim S.', null, '2026-05-30T09:00:00.000Z'::timestamptz, '2026-05-30T09:00:00.000Z'::timestamptz);

insert into changelog_entries (
  id, feature_id, kind, title_ar, title_en, body_ar, body_en,
  image_url, image_alt_ar, image_alt_en,
  article_url, action_url, action_label_ar, action_label_en,
  is_published, published_at
) values
  ('e1000000-0000-4000-8000-000000000001', 'f1000000-0000-4000-8000-000000000014', 'new', 'أطلقنا الرد السريع بالاختصارات', 'Saved replies with shortcuts are live',
   'احفظ ردودك المتكررة واستدعها بكتابة «/» متبوعة باختصار قصير. يوفّر ذلك على فرق الدعم آلاف الضغطات أسبوعيًا.

يمكنك إنشاء الردود من الإعدادات ومشاركتها مع الفريق كله أو إبقاؤها خاصة بك. الردود تدعم المتغيرات، فيمكنك إدراج اسم العميل أو رقم الطلب تلقائيًا داخل النص.

وإذا كان لديك أكثر من لغة، أنشئ نسخة عربية وأخرى إنجليزية للاختصار نفسه، وسيختار فلوفو المناسبة حسب لغة المحادثة.', 'Save your repeated answers and recall them by typing “/” plus a short shortcut. Thousands of keystrokes saved per week.

Create replies from settings and share them with the whole team or keep them to yourself. Replies support variables, so a customer''s name or an order number can be dropped into the text automatically.

If you work in more than one language, write an Arabic and an English version of the same shortcut and Flovoo picks the right one for the conversation.', '/updates/saved-replies.svg',
   'قائمة ردود محفوظة تظهر فوق مربع الكتابة، وبجانبه زر الاختصار «/».', 'A list of saved replies appearing above the composer, next to the “/” shortcut key.',
   'https://help.flovoo.com/ar/saved-replies', 'https://app.flovoo.com/settings/saved-replies', 'افتح الردود المحفوظة', 'Open saved replies',
   true, '2026-08-15T09:00:00.000Z'::timestamptz),
  ('e1000000-0000-4000-8000-000000000002', 'f1000000-0000-4000-8000-000000000015', 'new', 'إنستغرام المباشر وصل إلى صندوق الوارد', 'Instagram Direct has landed in your inbox',
   'الرسائل المباشرة والتعليقات أصبحت في المكان نفسه مع واتساب وماسنجر والرسائل النصية.

اربط حسابك من صفحة القنوات، وستبدأ الرسائل بالوصول خلال دقائق. التعليقات على منشوراتك تظهر كمحادثات أيضًا، فيمكن لفريقك الرد عليها ثم متابعة الحديث في الخاص دون مغادرة فلوفو.', 'Direct messages and comments now sit alongside WhatsApp, Messenger, and SMS in one place.

Connect your account from the channels page and messages start arriving within minutes. Comments on your posts show up as conversations too, so your team can reply and then continue in DMs without leaving Flovoo.', '/updates/instagram-inbox.svg',
   'أربع قنوات على اليمين تتجمع خطوطها في صندوق وارد واحد على اليسار.', 'Four channels on one side, their lines converging into a single inbox on the other.',
   null, 'https://app.flovoo.com/settings/channels', 'اربط إنستغرام', 'Connect Instagram',
   true, '2026-07-18T09:00:00.000Z'::timestamptz),
  ('e1000000-0000-4000-8000-000000000003', 'f1000000-0000-4000-8000-000000000016', 'improved', 'أدوار وصلاحيات لفريقك بالكامل', 'Roles and permissions for your whole team',
   'أضف زملاءك بأدوار مختلفة، وحدّد بدقة من يرى ماذا ومن يمكنه الرد على من.

ثلاثة أدوار جاهزة: مدير يرى كل شيء، وموظف دعم يرى المحادثات المسندة إليه وفريقه، ومراقب يقرأ دون أن يرد. يمكنك تغيير دور أي عضو في أي وقت دون التأثير على المحادثات الجارية.', 'Invite colleagues with distinct roles and control exactly who sees what and who can reply to whom.

Three roles out of the box: an admin who sees everything, an agent who sees their own and their team''s conversations, and a viewer who reads without replying. Change anyone''s role at any time without disturbing conversations in flight.', '/updates/roles-permissions.svg',
   'ثلاث بطاقات أدوار، كل واحدة تعرض عدداً أقل من الصلاحيات المفعّلة من التي قبلها.', 'Three role cards, each showing fewer enabled permissions than the one before it.',
   'https://help.flovoo.com/ar/roles-and-permissions', null, null, null,
   true, '2026-06-19T09:00:00.000Z'::timestamptz);

commit;
