/**
 * Generates `supabase/seed.sql` from `src/lib/data/seed.ts` so the local seed
 * data and the database seed can never drift apart.
 *
 *   npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  HELP_ARTICLES,
  HELP_COLLECTIONS,
  HELP_TRANSLATIONS,
} from "../src/lib/data/help-seed.ts";
import { CATEGORIES, CHANGELOG_ENTRIES, FEATURES } from "../src/lib/data/seed.ts";

const q = (value: string | null | undefined) =>
  value == null ? "null" : `'${value.replaceAll("'", "''")}'`;
const b = (value: boolean) => (value ? "true" : "false");
const ts = (value: string | null) => (value == null ? "null" : `'${value}'::timestamptz`);
// A null body stays SQL null; anything else is a jsonb literal.
const j = (value: unknown) =>
  value == null ? "null" : `${q(JSON.stringify(value))}::jsonb`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.",
  "-- Source of truth: src/lib/data/seed.ts   (regenerate with `npm run seed:sql`)",
  "-- Development data for the ROADMAP tables. It deletes them first, so it is",
  "-- never run against a project that holds real roadmap content.",
  "",
  "begin;",
  "",
  "delete from changelog_entries;",
  "delete from votes;",
  "delete from features;",
  "delete from categories;",
  "",
  "insert into categories (id, slug, name_ar, name_en, color, sort_order) values",
];

lines.push(
  CATEGORIES.map(
    (c) =>
      `  (${q(c.id)}, ${q(c.slug)}, ${q(c.name_ar)}, ${q(c.name_en)}, ${q(c.color)}, ${c.sort_order})`,
  ).join(",\n") + ";",
  "",
  "insert into features (",
  "  id, title_ar, title_en, description_ar, description_en, status, category_id,",
  "  vote_count, is_pinned, source, submitted_by_name, shipped_at, created_at, updated_at",
  ") values",
);

lines.push(
  FEATURES.map(
    (f) =>
      `  (${q(f.id)}, ${q(f.title_ar)}, ${q(f.title_en)}, ${q(f.description_ar)}, ${q(f.description_en)},\n` +
      `   ${q(f.status)}, ${q(f.category_id)}, ${f.vote_count}, ${b(f.is_pinned)}, ${q(f.source)},\n` +
      `   ${q(f.submitted_by_name)}, ${ts(f.shipped_at)}, ${ts(f.created_at)}, ${ts(f.updated_at)})`,
  ).join(",\n") + ";",
  "",
  "insert into changelog_entries (",
  "  id, feature_id, kind, title_ar, title_en, body_ar, body_en,",
  "  image_url, image_url_en, image_alt_ar, image_alt_en, cover_alt_needs_review,",
  "  article_url, action_url, action_label_ar, action_label_en,",
  "  is_published, published_at",
  ") values",
);

lines.push(
  CHANGELOG_ENTRIES.map(
    (e) =>
      `  (${q(e.id)}, ${q(e.feature_id)}, ${q(e.kind)}, ${q(e.title_ar)}, ${q(e.title_en)},\n` +
      `   ${j(e.body_ar)}, ${j(e.body_en)}, ${q(e.image_url)}, ${q(e.image_url_en)},\n` +
      `   ${q(e.image_alt_ar)}, ${q(e.image_alt_en)}, ${b(e.cover_alt_needs_review)},\n` +
      `   ${q(e.article_url)}, ${q(e.action_url)}, ${q(e.action_label_ar)}, ${q(e.action_label_en)},\n` +
      `   ${b(e.is_published)}, ${ts(e.published_at)})`,
  ).join(",\n") + ";",
  "",
  "commit;",
  "",
);

/**
 * The help center's seed is a separate file so it can be applied to a project
 * that already holds live roadmap data: it only ever touches `help_*` tables.
 */
const helpLines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.",
  "-- Source of truth: src/lib/data/help-seed.ts   (regenerate with `npm run seed:sql`)",
  "-- Sample help-center content. Replaces the help_* content tables only.",
  "",
  "begin;",
  "",
  "delete from help_article_translations;",
  "delete from help_articles;",
  "delete from help_collections;",
  "",
  "insert into help_collections (",
  "  id, slug, name_ar, name_en, description_ar, description_en, icon, sort_order,",
  "  is_published, created_at, updated_at",
  ") values",
];

helpLines.push(
  HELP_COLLECTIONS.map(
    (c) =>
      `  (${q(c.id)}, ${q(c.slug)}, ${q(c.name_ar)}, ${q(c.name_en)}, ${q(c.description_ar)}, ${q(c.description_en)},\n` +
      `   ${q(c.icon)}, ${c.sort_order}, ${b(c.is_published)}, ${ts(c.created_at)}, ${ts(c.updated_at)})`,
  ).join(",\n") + ";",
  "",
  "insert into help_articles (",
  "  id, collection_id, status, is_pinned, sort_order, section_ar, section_en, icon,",
  "  created_at, updated_at, published_at",
  ") values",
);

helpLines.push(
  HELP_ARTICLES.map(
    (a) =>
      `  (${q(a.id)}, ${q(a.collection_id)}, ${q(a.status)}, ${b(a.is_pinned)}, ${a.sort_order},\n` +
      `   ${q(a.section_ar)}, ${q(a.section_en)}, ${q(a.icon)},\n` +
      `   ${ts(a.created_at)}, ${ts(a.updated_at)}, ${ts(a.published_at)})`,
  ).join(",\n") + ";",
  "",
  "insert into help_article_translations (",
  "  id, article_id, language, slug, title, excerpt, body, body_plain,",
  "  meta_title, meta_description, og_image_path, toc, reading_minutes, created_at, updated_at",
  ") values",
);

helpLines.push(
  HELP_TRANSLATIONS.map(
    (t) =>
      `  (${q(t.id)}, ${q(t.article_id)}, ${q(t.language)}, ${q(t.slug)}, ${q(t.title)}, ${q(t.excerpt)},\n` +
      `   ${j(t.body)},\n` +
      `   ${q(t.body_plain)},\n` +
      `   ${q(t.meta_title)}, ${q(t.meta_description)}, ${q(t.og_image_path)}, ${j(t.toc)}, ${t.reading_minutes},\n` +
      `   ${ts(t.created_at)}, ${ts(t.updated_at)})`,
  ).join(",\n") + ";",
  "",
  "commit;",
  "",
);

const out = join(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`wrote ${out}`);

const helpOut = join(import.meta.dirname, "..", "supabase", "seed-help.sql");
writeFileSync(helpOut, helpLines.join("\n"), "utf8");
console.log(`wrote ${helpOut}`);
