/**
 * Generates `supabase/seed.sql` from `src/lib/data/seed.ts` so the local seed
 * data and the database seed can never drift apart.
 *
 *   npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { CATEGORIES, CHANGELOG_ENTRIES, FEATURES } from "../src/lib/data/seed.ts";

const q = (value: string | null | undefined) =>
  value == null ? "null" : `'${value.replaceAll("'", "''")}'`;
const b = (value: boolean) => (value ? "true" : "false");
const ts = (value: string | null) => (value == null ? "null" : `'${value}'::timestamptz`);

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.",
  "-- Source of truth: src/lib/data/seed.ts   (regenerate with `npm run seed:sql`)",
  "",
  "begin;",
  "",
  "delete from changelog_entries;",
  "delete from votes;",
  "delete from features;",
  "delete from categories;",
  "",
  "insert into categories (id, slug, name_ar, name_en, color, sort_order) values",
];

lines.push(
  CATEGORIES.map(
    (c) =>
      `  (${q(c.id)}, ${q(c.slug)}, ${q(c.name_ar)}, ${q(c.name_en)}, ${q(c.color)}, ${c.sort_order})`,
  ).join(",\n") + ";",
  "",
  "insert into features (",
  "  id, title_ar, title_en, description_ar, description_en, status, category_id,",
  "  vote_count, is_pinned, source, submitted_by_name, shipped_at, created_at, updated_at",
  ") values",
);

lines.push(
  FEATURES.map(
    (f) =>
      `  (${q(f.id)}, ${q(f.title_ar)}, ${q(f.title_en)}, ${q(f.description_ar)}, ${q(f.description_en)},\n` +
      `   ${q(f.status)}, ${q(f.category_id)}, ${f.vote_count}, ${b(f.is_pinned)}, ${q(f.source)},\n` +
      `   ${q(f.submitted_by_name)}, ${ts(f.shipped_at)}, ${ts(f.created_at)}, ${ts(f.updated_at)})`,
  ).join(",\n") + ";",
  "",
  "insert into changelog_entries (",
  "  id, feature_id, kind, title_ar, title_en, body_ar, body_en,",
  "  image_url, image_alt_ar, image_alt_en,",
  "  article_url, action_url, action_label_ar, action_label_en,",
  "  is_published, published_at",
  ") values",
);

lines.push(
  CHANGELOG_ENTRIES.map(
    (e) =>
      `  (${q(e.id)}, ${q(e.feature_id)}, ${q(e.kind)}, ${q(e.title_ar)}, ${q(e.title_en)},\n` +
      `   ${q(e.body_ar)}, ${q(e.body_en)}, ${q(e.image_url)},\n` +
      `   ${q(e.image_alt_ar)}, ${q(e.image_alt_en)},\n` +
      `   ${q(e.article_url)}, ${q(e.action_url)}, ${q(e.action_label_ar)}, ${q(e.action_label_en)},\n` +
      `   ${b(e.is_published)}, ${ts(e.published_at)})`,
  ).join(",\n") + ";",
  "",
  "commit;",
  "",
);

const out = join(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`wrote ${out}`);
